language: python
python:
  - 3.6
  - 3.7
  - 3.8

git:
  depth: 3
install:
  - pip install --ignore-installed -e ./src
  - pip install --ignore-installed -r requirements.txt
before_script:
  - python scripts/check_and_use_custom_sdk.py
  - sfctl settings telemetry set-telemetry --off
script:
  - scripts/verify.sh test
  - scripts/verify.sh lint
after_success:
  - coveralls
branches:
  only:
    - master


